/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2016-06-24 13:55:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.BenhNhan;

public final class header1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");

	BenhNhan bn = (BenhNhan) session.getAttribute("currentUser");

      out.write("   \r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<span>Đảm bảo sức khỏe sinh sản phụ nữ...</span> <a href=\"index.jsp\"\r\n");
      out.write("\t\t\tclass=\"logo\"><img src=\"images/logo.png\" alt=\"\"></a> <span\r\n");
      out.write("\t\t\tclass=\"tagline\">Làm mẹ là điều tuyệt vời nhất!</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li class=\"selected\"><a href=\"index.jsp\">Trang chủ</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"about.jsp\">Giới thiệu</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"doctors.jsp\">Bác sĩ</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"services.jsp\">Dịch vụ</a></li>\r\n");
      out.write("\t\t\t");
 if (bn == null) 
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"forms.jsp\">Đăng ký</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"contact.jsp\">Liên hệ</a></li>\r\n");
      out.write("\t\t\t");
 if (bn == null) 
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"blog.jsp\">Đăng nhập</a></li>\r\n");
      out.write("\t\t\t");
 if (bn != null) { 
      out.write("\r\n");
      out.write("\t\t\t\t<h2>Xin chào, ");
      out.print(bn.getHoTen() );
      out.write("</h2>\r\n");
      out.write("\t\t\t\t<a style=\"font-size: 24px\" href=\"DangNhapServlet?command=dangxuat\">Đăng xuất</a>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\t\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
